
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: ErosJelszo123!
      MYSQL_ROOT_PASSWORD: RootJelszo123!
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./storage/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  glpi:
    image: glpi/glpi:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GLPI_DB_HOST: db
      GLPI_DB_PORT: 3306
      GLPI_DB_NAME: glpi
      GLPI_DB_USER: glpi
      GLPI_DB_PASSWORD: ErosJelszo123!
    volumes:
      - ./storage/glpi:/var/glpi
    ports:
      - "8080:80"

